#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export COMPASSLM_HOME="$(cd "${SCRIPT_DIR}/.." && pwd)"
source "${SCRIPT_DIR}/load_gpu_env.sh"

PORT_OVERRIDE_SET=0
AUTO_PORT_OVERRIDE_SET=0
[[ -n "${API_PORT+x}" ]] && PORT_OVERRIDE_SET=1 && API_PORT_OVERRIDE="${API_PORT}"
[[ -n "${COMPASS_AUTO_PORT+x}" ]] && AUTO_PORT_OVERRIDE_SET=1 && AUTO_PORT_OVERRIDE="${COMPASS_AUTO_PORT}"

compass_load_env_file "${MAIN_BACKEND_HOME}/.env.auto"
compass_load_env_file "${PROJECT_GPU_HOME}/runtime.env"
compass_load_env_file "${MAIN_BACKEND_HOME}/.env"
[[ "${PORT_OVERRIDE_SET}" == "1" ]] && API_PORT="${API_PORT_OVERRIDE}"
[[ "${AUTO_PORT_OVERRIDE_SET}" == "1" ]] && COMPASS_AUTO_PORT="${AUTO_PORT_OVERRIDE}"
export PADDLE_PDX_DISABLE_MODEL_SOURCE_CHECK="${PADDLE_PDX_DISABLE_MODEL_SOURCE_CHECK:-True}"
export PDF_OCR_ALLOW_ONLINE_MODEL_FALLBACK="${PDF_OCR_ALLOW_ONLINE_MODEL_FALLBACK:-0}"
export PDF_OCR_OPTIMIZATION_PROFILE="${PDF_OCR_OPTIMIZATION_PROFILE:-h100_96gb_fast}"
export PDF_OCR_USE_INTERNAL_QUEUES="${PDF_OCR_USE_INTERNAL_QUEUES:-1}"
export PDF_OCR_GPU_PROCESS_ISOLATION="${PDF_OCR_GPU_PROCESS_ISOLATION:-1}"
export PDF_OCR_WARMUP_ON_STARTUP="${PDF_OCR_WARMUP_ON_STARTUP:-1}"
export PDF_OCR_PERSISTENT_WORKER="${PDF_OCR_PERSISTENT_WORKER:-1}"
export PDF_OCR_PERSISTENT_WORKERS="${PDF_OCR_PERSISTENT_WORKERS:-1}"
export PDF_OCR_USE_CHART_RECOGNITION="${PDF_OCR_USE_CHART_RECOGNITION:-0}"
export PDF_OCR_USE_SEAL_RECOGNITION="${PDF_OCR_USE_SEAL_RECOGNITION:-0}"
export PDF_OCR_USE_OCR_FOR_IMAGE_BLOCK="${PDF_OCR_USE_OCR_FOR_IMAGE_BLOCK:-0}"
export PDF_OCR_MAX_NEW_TOKENS="${PDF_OCR_MAX_NEW_TOKENS:-768}"
export PDF_OCR_MIN_PIXELS="${PDF_OCR_MIN_PIXELS:-3136}"
export PDF_OCR_MAX_PIXELS="${PDF_OCR_MAX_PIXELS:-786432}"
export PDF_OCR_LAYOUT_SHAPE_MODE="${PDF_OCR_LAYOUT_SHAPE_MODE:-rect}"
export PDF_OCR_VL_REC_MAX_CONCURRENCY="${PDF_OCR_VL_REC_MAX_CONCURRENCY:-1}"
export PDF_ANSWER_PATH_LAZY_OCR_ENABLED="${PDF_ANSWER_PATH_LAZY_OCR_ENABLED:-0}"
export PDF_PARSE_MODE="${PDF_PARSE_MODE:-ocr_first}"
export PDF_UPLOAD_OCR_ENABLED="${PDF_UPLOAD_OCR_ENABLED:-1}"
export PDF_BACKGROUND_OCR_ENABLED="${PDF_BACKGROUND_OCR_ENABLED:-0}"
export PDF_OCR_DEVICE="${PDF_OCR_DEVICE:-gpu:0}"
export BACKEND_PADDLE_RUNTIME_KIND="${BACKEND_PADDLE_RUNTIME_KIND:-gpu}"
export BACKEND_PADDLE_CUDA_TRACK="${BACKEND_PADDLE_CUDA_TRACK:-cu126}"
export PDF_OCR_STRICT_GPU_COMPAT="${PDF_OCR_STRICT_GPU_COMPAT:-1}"
export PDF_OCR_GPU_FALLBACK_TO_CPU="${PDF_OCR_GPU_FALLBACK_TO_CPU:-0}"
export PDF_OCR_MAX_PAGES="${PDF_OCR_MAX_PAGES:-400}"
export PDF_OCR_GPU_BUDGET_GB="${PDF_OCR_GPU_BUDGET_GB:-${PDF_OCR_GPU_MEMORY_LIMIT_GB:-40}}"
export PDF_OCR_GPU_INITIAL_MEMORY_MB="${PDF_OCR_GPU_INITIAL_MEMORY_MB:-2048}"
export PDF_OCR_GPU_REALLOCATE_MEMORY_MB="${PDF_OCR_GPU_REALLOCATE_MEMORY_MB:-1024}"
export PDF_OCR_GPU_ALLOCATOR_STRATEGY="${PDF_OCR_GPU_ALLOCATOR_STRATEGY:-auto_growth}"
export PDF_OCR_PARALLEL_MAX_WORKERS="${PDF_OCR_PARALLEL_MAX_WORKERS:-1}"
export PDF_OCR_PARALLEL_MIN_PAGES="${PDF_OCR_PARALLEL_MIN_PAGES:-1}"
export PDF_OCR_EXEC_BATCH_PAGES="${PDF_OCR_EXEC_BATCH_PAGES:-3}"
export PDF_OCR_GPU_BATCH_TIMEOUT_SECONDS="${PDF_OCR_GPU_BATCH_TIMEOUT_SECONDS:-420}"
export PDF_OCR_GPU_SINGLE_BATCH_TIMEOUT_SECONDS="${PDF_OCR_GPU_SINGLE_BATCH_TIMEOUT_SECONDS:-240}"
export PDF_OCR_PROGRESS_HEARTBEAT_SECONDS="${PDF_OCR_PROGRESS_HEARTBEAT_SECONDS:-5}"
export PDF_OCR_TARGET_PAGES="${PDF_OCR_TARGET_PAGES:-200}"
export PDF_OCR_TARGET_SECONDS="${PDF_OCR_TARGET_SECONDS:-300}"

API_HOST="${API_HOST:-127.0.0.1}"
API_PORT_START="${API_PORT_START:-${API_PORT:-8004}}"
API_PORT="$(compass_select_service_port backend "${API_PORT_START}" "${API_PORT:-${API_PORT_START}}")"
COMPASSLM_BASE_URL_SELECTED="http://127.0.0.1:${API_PORT}"
API_RELOAD="${API_RELOAD:-0}"
VENV_PATH="${MAIN_BACKEND_HOME}/compassvenv"

if [[ ! -f "${VENV_PATH}/bin/activate" ]]; then
  echo "[ERROR] Main-backend venv not found: ${VENV_PATH}" >&2
  echo "Run: ${PROJECT_GPU_HOME}/setup_gpu_track.sh" >&2
  exit 1
fi

export EMBEDDING_PROVIDER="${EMBEDDING_PROVIDER:-api}"
if ! LIVE_EMBEDDING_API_URL="$(compass_require_live_embedding_url)"; then
  echo "[ERROR] Backend startup aborted because the embedding provider is not ready." >&2
  exit 1
fi
if ! LIVE_LLM_API_URL="$(compass_require_live_llm_url)"; then
  echo "[ERROR] Backend startup aborted because the LLM provider is not ready." >&2
  exit 1
fi
export EMBEDDING_API_URL="${LIVE_EMBEDDING_API_URL}"
export LLM_API_URL="${LIVE_LLM_API_URL}"
echo "[INFO] API_HOST=${API_HOST} API_PORT=${API_PORT} API_RELOAD=${API_RELOAD}"
echo "[INFO] EMBEDDING_PROVIDER=${EMBEDDING_PROVIDER}"
echo "[INFO] EMBEDDING_API_URL=${EMBEDDING_API_URL:-}"
echo "[INFO] LLM_API_URL=${LLM_API_URL:-}"
echo "[INFO] LLM_CTX_SIZE=${LLM_CTX_SIZE:-}"
echo "[INFO] LLM_CONTEXT_LIMIT=${LLM_CONTEXT_LIMIT:-}"
echo "[INFO] PDF_PARSE_MODE=${PDF_PARSE_MODE}"
echo "[INFO] PDF_TEXT_EXTRACTOR=${PDF_TEXT_EXTRACTOR:-pymupdf}"
echo "[INFO] PDF_OCR_MODEL_NAME=${PDF_OCR_MODEL_NAME:-}"
echo "[INFO] PDF_OCR_ALLOW_ONLINE_MODEL_FALLBACK=${PDF_OCR_ALLOW_ONLINE_MODEL_FALLBACK}"
echo "[INFO] PDF_OCR_OPTIMIZATION_PROFILE=${PDF_OCR_OPTIMIZATION_PROFILE}"
echo "[INFO] PDF_OCR_USE_INTERNAL_QUEUES=${PDF_OCR_USE_INTERNAL_QUEUES}"
echo "[INFO] PDF_OCR_GPU_PROCESS_ISOLATION=${PDF_OCR_GPU_PROCESS_ISOLATION}"
echo "[INFO] PDF_OCR_WARMUP_ON_STARTUP=${PDF_OCR_WARMUP_ON_STARTUP}"
echo "[INFO] PDF_OCR_PERSISTENT_WORKER=${PDF_OCR_PERSISTENT_WORKER}"
echo "[INFO] PDF_OCR_PERSISTENT_WORKERS=${PDF_OCR_PERSISTENT_WORKERS}"
echo "[INFO] PDF_OCR_USE_CHART_RECOGNITION=${PDF_OCR_USE_CHART_RECOGNITION:-}"
echo "[INFO] PDF_OCR_USE_SEAL_RECOGNITION=${PDF_OCR_USE_SEAL_RECOGNITION:-}"
echo "[INFO] PDF_OCR_USE_OCR_FOR_IMAGE_BLOCK=${PDF_OCR_USE_OCR_FOR_IMAGE_BLOCK:-}"
echo "[INFO] PDF_OCR_MAX_NEW_TOKENS=${PDF_OCR_MAX_NEW_TOKENS:-}"
echo "[INFO] PDF_OCR_MIN_PIXELS=${PDF_OCR_MIN_PIXELS:-}"
echo "[INFO] PDF_OCR_MAX_PIXELS=${PDF_OCR_MAX_PIXELS:-}"
echo "[INFO] PDF_OCR_LAYOUT_SHAPE_MODE=${PDF_OCR_LAYOUT_SHAPE_MODE:-}"
echo "[INFO] PDF_OCR_VL_REC_MAX_CONCURRENCY=${PDF_OCR_VL_REC_MAX_CONCURRENCY:-}"
echo "[INFO] PDF_OCR_ENGINE=${PDF_OCR_ENGINE:-}"
echo "[INFO] PDF_ANSWER_PATH_LAZY_OCR_ENABLED=${PDF_ANSWER_PATH_LAZY_OCR_ENABLED}"
echo "[INFO] PDF_UPLOAD_OCR_ENABLED=${PDF_UPLOAD_OCR_ENABLED}"
echo "[INFO] PDF_BACKGROUND_OCR_ENABLED=${PDF_BACKGROUND_OCR_ENABLED}"
echo "[INFO] PDF_OCR_MAX_PAGES=${PDF_OCR_MAX_PAGES}"
echo "[INFO] PDF_OCR_DEVICE=${PDF_OCR_DEVICE}"
echo "[INFO] BACKEND_PADDLE_RUNTIME_KIND=${BACKEND_PADDLE_RUNTIME_KIND}"
echo "[INFO] PDF_OCR_GPU_FALLBACK_TO_CPU=${PDF_OCR_GPU_FALLBACK_TO_CPU}"
echo "[INFO] PDF_OCR_GPU_BUDGET_GB=${PDF_OCR_GPU_BUDGET_GB}"
echo "[INFO] PDF_OCR_GPU_INITIAL_MEMORY_MB=${PDF_OCR_GPU_INITIAL_MEMORY_MB}"
echo "[INFO] PDF_OCR_GPU_REALLOCATE_MEMORY_MB=${PDF_OCR_GPU_REALLOCATE_MEMORY_MB}"
echo "[INFO] PDF_OCR_GPU_ALLOCATOR_STRATEGY=${PDF_OCR_GPU_ALLOCATOR_STRATEGY}"
echo "[INFO] PDF_OCR_PARALLEL_MAX_WORKERS=${PDF_OCR_PARALLEL_MAX_WORKERS}"
echo "[INFO] PDF_OCR_PARALLEL_MIN_PAGES=${PDF_OCR_PARALLEL_MIN_PAGES}"
echo "[INFO] PDF_OCR_EXEC_BATCH_PAGES=${PDF_OCR_EXEC_BATCH_PAGES}"
echo "[INFO] PDF_OCR_GPU_BATCH_TIMEOUT_SECONDS=${PDF_OCR_GPU_BATCH_TIMEOUT_SECONDS}"
echo "[INFO] PDF_OCR_GPU_SINGLE_BATCH_TIMEOUT_SECONDS=${PDF_OCR_GPU_SINGLE_BATCH_TIMEOUT_SECONDS}"
echo "[INFO] PDF_OCR_PROGRESS_HEARTBEAT_SECONDS=${PDF_OCR_PROGRESS_HEARTBEAT_SECONDS}"
echo "[INFO] PDF_OCR_TARGET_PAGES=${PDF_OCR_TARGET_PAGES}"
echo "[INFO] PDF_OCR_TARGET_SECONDS=${PDF_OCR_TARGET_SECONDS}"
echo "[INFO] PYDANTIC_AI_PROVIDER_KIND=${PYDANTIC_AI_PROVIDER_KIND:-openai_compatible}"
echo "[INFO] PYDANTIC_AI_PROVIDER_LABEL=${PYDANTIC_AI_PROVIDER_LABEL:-}"
echo "[INFO] PYDANTIC_AI_HISTORY_STRATEGY=${PYDANTIC_AI_HISTORY_STRATEGY:-compact_text}"
echo "[INFO] PADDLE_PDX_DISABLE_MODEL_SOURCE_CHECK=${PADDLE_PDX_DISABLE_MODEL_SOURCE_CHECK}"
echo "[PORT] Backend:   ${COMPASSLM_BASE_URL_SELECTED}/"
echo "[PORT] Embedding: ${EMBEDDING_API_URL:-<not-running>}"
echo "[PORT] LLM:       ${LLM_API_URL:-<not-running>}"
echo "[PORT] Proxy:     https://<host>:8000/user/<user>/proxy/${API_PORT}/"

cd "${COMPASSLM_HOME}"
source "${VENV_PATH}/bin/activate"

if [[ "${API_RELOAD}" == "1" ]]; then
  python -m uvicorn src.main:app --host "${API_HOST}" --port "${API_PORT}" --reload &
else
  python -m uvicorn src.main:app --host "${API_HOST}" --port "${API_PORT}" &
fi
BACKEND_SERVER_PID="$!"
trap 'kill "${BACKEND_SERVER_PID}" 2>/dev/null || true' INT TERM EXIT
if ! compass_wait_for_backend_ready "${COMPASSLM_BASE_URL_SELECTED}" "${BACKEND_SERVER_PID}"; then
  kill "${BACKEND_SERVER_PID}" 2>/dev/null || true
  wait "${BACKEND_SERVER_PID}" 2>/dev/null || true
  exit 1
fi
compass_write_service_state backend "${API_PORT}" "${COMPASSLM_BASE_URL_SELECTED}" "${BACKEND_SERVER_PID}"
wait "${BACKEND_SERVER_PID}"
